# -*- coding: utf-8 -*-
"""Dropshipping_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGN6rjolPBI2bP9vFEKraHSkAn1LrIKF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (12, 6)
plt.rcParams["axes.grid"] = True

df = pd.read_csv("/content/dropshipping_model_dataset_1000.csv")
print(df.shape)
df.head(10)

def find_by_hints(df, hints):
    for h in hints:
        for c in df.columns:
            if h in c.lower():
                return c
    return None

def infer_columns(df):
    lower_cols = [c.lower() for c in df.columns]
    info = {}
    info["date"] = find_by_hints(df, ["date", "order_date", "created", "timestamp", "day"])
    info["product"] = find_by_hints(df, ["product", "title", "name", "sku", "asin"])
    info["category"] = find_by_hints(df, ["category", "type"])
    info["orders"] = find_by_hints(df, ["qty", "quantity", "units", "orders", "sold", "sales_count", "order"])
    info["revenue"] = find_by_hints(df, ["revenue", "sales", "gmv", "amount", "turnover"])
    info["price"] = find_by_hints(df, ["price", "selling_price", "sale_price"])
    info["cost"] = find_by_hints(df, ["cost", "cogs", "buy_cost"])
    info["returns"] = find_by_hints(df, ["return", "refund"])
    info["rating"] = find_by_hints(df, ["rating", "review", "stars"])
    info["region"] = find_by_hints(df, ["country", "region", "market", "city", "state", "geo"])
    info["stock"] = find_by_hints(df, ["stock", "inventory", "on_hand"])
    info["numeric_cols"] = df.select_dtypes(include=[np.number]).columns.tolist()
    return info

info = infer_columns(df)
info

# --- Basic cleaning & optional date coercion ---
dfx = df.copy()
if info["date"]:
    dfx[info["date"]] = pd.to_datetime(dfx[info["date"]], errors="coerce")
    dfx = dfx.dropna(subset=[info["date"]])
dfx.head()

"""## KPI Summary"""

# --- KPI calculations ---
rev = dfx[info["revenue"]].sum() if info["revenue"] and info["revenue"] in dfx.columns else np.nan
orders = dfx[info["orders"]].sum() if info["orders"] and info["orders"] in dfx.columns else np.nan
avg_order = (rev / orders) if np.isfinite(rev) and np.isfinite(orders) and orders else np.nan

profit = np.nan
if info["revenue"] and info["cost"] and info["revenue"] in dfx.columns and info["cost"] in dfx.columns:
    profit = (dfx[info["revenue"]] - dfx[info["cost"]]).sum()

kpis = {
    "Revenue": rev if np.isfinite(rev) else None,
    "Orders": orders if np.isfinite(orders) else None,
    "Avg Order Value": avg_order if np.isfinite(avg_order) else None,
    "Profit": profit if np.isfinite(profit) else None,
}
kpis

"""## Trend over Time"""

# --- Time series plot (matplotlib, single plot) ---
metric = info["orders"] or info["revenue"]
if info["date"] and metric and metric in dfx.columns:
    daily = dfx.groupby(dfx[info["date"]].dt.to_period("D"))[metric].sum().reset_index()
    daily[info["date"]] = daily[info["date"]].dt.to_timestamp()

    plt.figure()
    plt.plot(daily[info["date"]], daily[metric])
    plt.title(f"Daily {metric} over time")
    plt.xlabel("Date")
    plt.ylabel(metric)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()
else:
    print("No suitable date/metric columns found for a time series.")

"""## Top Products"""

# --- Top products bar chart ---
metric = info["orders"] or info["revenue"] or (info["numeric_cols"][0] if info["numeric_cols"] else None)
if info["product"] and metric and metric in dfx.columns:
    topn = (
        dfx.groupby(info["product"])[metric]
        .sum()
        .sort_values(ascending=False)
        .head(20)
        .reset_index()
    )

    plt.figure()
    plt.bar(topn[info["product"]].astype(str), topn[metric])
    plt.title(f"Top products by {metric}")
    plt.ylabel(metric)
    plt.xticks(rotation=75, ha="right")
    plt.tight_layout()
    plt.show()
else:
    print("No product/metric columns found for top products.")

"""## Category Mix"""

# --- Category mix (bar) ---
metric = info["orders"] or info["revenue"] or (info["numeric_cols"][0] if info["numeric_cols"] else None)
if info["category"] and metric and metric in dfx.columns:
    mix = dfx.groupby(info["category"])[metric].sum().reset_index()

    plt.figure()
    plt.bar(mix[info["category"]].astype(str), mix[metric])
    plt.title(f"Category mix by {metric}")
    plt.ylabel(metric)
    plt.xticks(rotation=75, ha="right")
    plt.tight_layout()
    plt.show()
else:
    print("No category/metric columns found for category mix.")

"""## Region Performance"""

# --- Region performance (bar) ---
metric = info["orders"] or info["revenue"] or (info["numeric_cols"][0] if info["numeric_cols"] else None)
if info["region"] and metric and metric in dfx.columns:
    geo = dfx.groupby(info["region"])[metric].sum().reset_index()

    plt.figure()
    plt.bar(geo[info["region"]].astype(str), geo[metric])
    plt.title(f"Region performance by {metric}")
    plt.ylabel(metric)
    plt.xticks(rotation=75, ha="right")
    plt.tight_layout()
    plt.show()
else:
    print("No region/metric columns found for region performance.")

"""
---

### Optional: Interactive Plotly (uncomment to use)
The notebook above uses matplotlib to comply with environments that forbid styling changes.  
If you want interactive charts, you can use Plotly by uncommenting and running the next cell.
"""

# # Uncomment to enable interactive charts
import plotly.express as px
metric = info["orders"] or info["revenue"]
if info["date"] and metric and metric in dfx.columns:
    ts = dfx.copy()
    ts[info["date"]] = pd.to_datetime(ts[info["date"]], errors="coerce")
    daily = ts.groupby(ts[info["date"]].dt.to_period("D"))[metric].sum().reset_index()
    daily[info["date"]] = daily[info["date"]].dt.to_timestamp()
    fig = px.line(daily, x=info["date"], y=metric, markers=True)
    fig.show()